[Setup]
AppName=SnapCam
AppVersion=1.0
Publisher=SnapCam Project
DefaultDirName={autopf}\SnapCam
DefaultGroupName=SnapCam
OutputDir=Output
OutputBaseFilename=SnapCam_Setup_v1.0
SetupIconFile=snapcam.ico
Compression=lzma2
SolidCompression=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
; Include the entire dist/SnapCam folder generated by PyInstaller
Source: "dist\SnapCam\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\SnapCam"; Filename: "{app}\SnapCam.exe"; IconFilename: "{app}\snapcam.ico"
Name: "{autodesktop}\SnapCam"; Filename: "{app}\SnapCam.exe"; IconFilename: "{app}\snapcam.ico"; Tasks: desktopicon

[Run]
; Optionally launch the app after install
Filename: "{app}\SnapCam.exe"; Description: "Launch SnapCam"; Flags: nowait postinstall skipifsilent

[Code]
// If you want to automatically execute the driver registration on install:
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    // Run the bat file to install the virtual camera driver
    // We use ShellExec to trigger the UAC prompt internally by the bat if needed, 
    // but the installer itself is already running as Admin.
    Exec(ExpandConstant('{app}\install_vcam_driver.bat'), '', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;
